---
- name: config_samba | disabling samba service  #ctdb will manage samba
  service:
    name: "samba"
    enabled: no
    state: stopped
  notify:
    - restart ctdb
  when: ansible_distribution == "Debian"

- name: config_samba | disabling samba service
  service:
    name: "smb"
    enabled: no
    state: stopped
  notify:
    - restart ctdb
  when: ansible_distribution == "RedHat"

- name: config_samba | configuring samba
  template:
    src: "etc/samba/smb.conf.j2"
    dest: "/etc/samba/smb.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ctdb

- name: config_samba | configuring nssswitch
  template:
    src: "etc/nsswitch.conf.j2"
    dest: "/etc/nsswitch.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ctdb

- name: config_samba | disabling winbind service  #ctdb will manage
  service:
    name: "winbind"
    enabled: no
    state: stopped
  when: ctdb_manages_winbind

- name: config_samba | configuring KRB5
  template:
    src: "etc/krb5.conf.j2"
    dest: "/etc/krb5.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ctdb
